language: php
sudo: required
php:
  - "5.5"

before_script:
  - composer install
  - sudo apt-get install xvfb
  - sudo apt-get install firefox
#  - npm install -g phantomjs
#  - "phantomjs --webdriver=8324 > /dev/null &"
  - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
  - "DISPLAY=:10 xvfb-run java -jar selenium-server-standalone-2.45.0.jar > /dev/null &"
  - sleep 5

script:
  - php ./bin/behat
