language: php
php:
  - "5.5"

before_script:
  - composer install
  - npm install -g phantomjs
  - "phantomjs --webdriver=8324"
  - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
  - "java -jar selenium-server-standalone-2.45.0.jar > /dev/null &"
  - sleep 5

script:
  - php ./bin/behat -p phantomjs
